<?php

namespace LoxBerry\System;

/**
 * Class Paths.
 */
class Paths
{
    const PATH_LB_HOME = 'LBHOMEDIR';

    const PATH_SYSTEM_HTMLAUTH = 'LBSHTMLAUTHDIR';
    const PATH_SYSTEM_HTML = 'LBSHTMLDIR';
    const PATH_SYSTEM_TEMPLATE = 'LBSTEMPLATEDIR';
    const PATH_SYSTEM_DATA = 'LBSDATADIR';
    const PATH_SYSTEM_LOG = 'LBSLOGDIR';
    const PATH_SYSTEM_TMPFSLOG = 'LBSTMPFSLOGDIR';
    const PATH_SYSTEM_CONFIG = 'LBSCONFIGDIR';
    const PATH_SYSTEM_SBIN = 'LBSSBINDIR';
    const PATH_SYSTEM_BIN = 'LBSBINDIR';

    const PATH_PLUGIN_HTMLAUTH = 'LBPHTMLAUTHDIR';
    const PATH_PLUGIN_HTML = 'LBPHTMLDIR';
    const PATH_PLUGIN_TEMPLATE = 'LBPTEMPLATEDIR';
    const PATH_PLUGIN_DATA = 'LBPDATADIR';
    const PATH_PLUGIN_LOG = 'LBPLOGDIR';
    const PATH_PLUGIN_CONFIG = 'LBPCONFIGDIR';
    const PATH_PLUGIN_BIN = 'LBPBINDIR';

    const PATH_LOG_DATABASE_FILE = 'LOG_DATABASE_FILE';
    const PATH_PLUGIN_DATABASE_FILE = 'PLUGIN_DATABASE_FILE';
    const PATH_REBOOT_REQUIRED_FILE = 'REBOOT_REQUIRED_FILE';
    const PATH_CENTRAL_CONFIG_FILE = 'CENTRAL_CONFIG_FILE';
}
